#!/usr/bin/env bash
set -Eeuo pipefail

export GOTRUE_API_HOST="${GOTRUE_API_HOST:-0.0.0.0}"
export GOTRUE_API_PORT="${GOTRUE_API_PORT:-9999}"
export GOTRUE_DB_DRIVER="${GOTRUE_DB_DRIVER:-postgres}"

export GOTRUE_DB_DATABASE_URL="${GOTRUE_DB_DATABASE_URL:-postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"

export GOTRUE_JWT_ADMIN_ROLES="${GOTRUE_JWT_ADMIN_ROLES:-service_role}"
export GOTRUE_JWT_AUD="${GOTRUE_JWT_AUD:-authenticated}"
export GOTRUE_JWT_DEFAULT_GROUP_NAME="${GOTRUE_JWT_DEFAULT_GROUP_NAME:-authenticated}"

export JWT_EXPIRY="${JWT_EXPIRY:-3600}"
export SITE_URL="${SITE_URL:-http://localhost:3000}"
export ADDITIONAL_REDIRECT_URLS="${ADDITIONAL_REDIRECT_URLS:-}"
export DISABLE_SIGNUP="${DISABLE_SIGNUP:-false}"
export DISABLE_SIGNUP="${DISABLE_SIGNUP:-false}"
export API_EXTERNAL_URL="${API_EXTERNAL_URL:-http://localhost:8000}"

export MAILER_URLPATHS_CONFIRMATION="${MAILER_URLPATHS_CONFIRMATION:-/auth/v1/verify}"
export MAILER_URLPATHS_INVITE="${MAILER_URLPATHS_INVITE:-/auth/v1/verify}"
export MAILER_URLPATHS_RECOVERY="${MAILER_URLPATHS_RECOVERY:-/auth/v1/verify}"
export MAILER_URLPATHS_EMAIL_CHANGE="${MAILER_URLPATHS_EMAIL_CHANGE:-/auth/v1/verify}"

export ENABLE_EMAIL_SIGNUP="${ENABLE_EMAIL_SIGNUP:-true}"

export ENABLE_EMAIL_AUTOCONFIRM="${ENABLE_EMAIL_AUTOCONFIRM:-false}"
export SMTP_ADMIN_EMAIL="${SMTP_ADMIN_EMAIL:-admin@example.com}"

export SMTP_HOST="${SMTP_HOST:-supabase-mail}"
export SMTP_PORT="${SMTP_PORT:-2500}"
export SMTP_USER="${SMTP_USER:-fake_mail_user}"
export SMTP_PASS="${SMTP_PASS:-fake_mail_password}"

export SMTP_SENDER_NAME="${SMTP_SENDER_NAME:-fake_sender}"
export ENABLE_ANONYMOUS_USERS="${ENABLE_ANONYMOUS_USERS:-false}"

export ENABLE_PHONE_SIGNUP="${ENABLE_PHONE_SIGNUP:-true}"
export ENABLE_PHONE_AUTOCONFIRM="${ENABLE_PHONE_AUTOCONFIRM:-true}"

if [ -n "${SITE_URL:-}" ]; then
  export GOTRUE_SITE_URL="${SITE_URL}"
fi

if [ -n "${ADDITIONAL_REDIRECT_URLS:-}" ]; then
  export GOTRUE_URI_ALLOW_LIST="${ADDITIONAL_REDIRECT_URLS}"
fi

if [ -n "${DISABLE_SIGNUP:-}" ]; then
  export GOTRUE_DISABLE_SIGNUP="${DISABLE_SIGNUP}"
fi

if [ -n "${JWT_EXPIRY:-}" ]; then
  export GOTRUE_JWT_EXP="${JWT_EXPIRY}"
fi

if [ -n "${JWT_SECRET:-}" ]; then
  export GOTRUE_JWT_SECRET="${JWT_SECRET}"
fi

if [ -n "${ENABLE_EMAIL_SIGNUP:-}" ]; then
  export GOTRUE_EXTERNAL_EMAIL_ENABLED="${ENABLE_EMAIL_SIGNUP}"
fi

if [ -n "${ENABLE_ANONYMOUS_USERS:-}" ]; then
  export GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED="${ENABLE_ANONYMOUS_USERS}"
fi

if [ -n "${ENABLE_EMAIL_AUTOCONFIRM:-}" ]; then
  export GOTRUE_MAILER_AUTOCONFIRM="${ENABLE_EMAIL_AUTOCONFIRM}"
fi

if [ -n "${SMTP_ADMIN_EMAIL:-}" ]; then
  export GOTRUE_SMTP_ADMIN_EMAIL="${SMTP_ADMIN_EMAIL}"
fi

if [ -n "${SMTP_ADMIN_EMAIL:-}" ]; then
  export GOTRUE_SMTP_ADMIN_EMAIL="${SMTP_ADMIN_EMAIL}"
fi

if [ -n "${SMTP_HOST:-}" ]; then
  export GOTRUE_SMTP_HOST="${SMTP_HOST}"
fi

if [ -n "${SMTP_PORT:-}" ]; then
  export GOTRUE_SMTP_PORT="${SMTP_PORT}"
fi

if [ -n "${SMTP_USER:-}" ]; then
  export GOTRUE_SMTP_USER="${SMTP_USER}"
fi

if [ -n "${SMTP_PASS:-}" ]; then
  export GOTRUE_SMTP_PASS="${SMTP_PASS}"
fi

if [ -n "${SMTP_SENDER_NAME:-}" ]; then
  export GOTRUE_SMTP_SENDER_NAME="${SMTP_SENDER_NAME}"
fi

if [ -n "${MAILER_URLPATHS_INVITE:-}" ]; then
  export GOTRUE_MAILER_URLPATHS_INVITE="${MAILER_URLPATHS_INVITE}"
fi

if [ -n "${MAILER_URLPATHS_CONFIRMATION:-}" ]; then
  export GOTRUE_MAILER_URLPATHS_CONFIRMATION="${MAILER_URLPATHS_CONFIRMATION}"
fi

if [ -n "${MAILER_URLPATHS_RECOVERY:-}" ]; then
  export GOTRUE_MAILER_URLPATHS_RECOVERY="${MAILER_URLPATHS_RECOVERY}"
fi

if [ -n "${MAILER_URLPATHS_EMAIL_CHANGE:-}" ]; then
  export GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE="${MAILER_URLPATHS_EMAIL_CHANGE}"
fi

if [ -n "${ENABLE_PHONE_SIGNUP:-}" ]; then
  export GOTRUE_EXTERNAL_PHONE_ENABLED="${ENABLE_PHONE_SIGNUP}"
fi

if [ -n "${ENABLE_PHONE_AUTOCONFIRM:-}" ]; then
  export GOTRUE_SMS_AUTOCONFIRM="${ENABLE_PHONE_AUTOCONFIRM}"
fi

exec "${@}"