#!/bin/sh
set -eu

export GOTRUE_DB_DATABASE_URL="${GOTRUE_DB_DATABASE_URL:-postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"

export GOTRUE_SITE_URL="${GOTRUE_SITE_URL:-$SITE_URL}"
export GOTRUE_URI_ALLOW_LIST="${GOTRUE_URI_ALLOW_LIST:-$ADDITIONAL_REDIRECT_URLS}"

export GOTRUE_DISABLE_SIGNUP="${GOTRUE_DISABLE_SIGNUP:-$DISABLE_SIGNUP}"

export GOTRUE_JWT_EXP="${GOTRUE_JWT_EXP:-$JWT_EXPIRY}"
export GOTRUE_JWT_SECRET="${GOTRUE_JWT_SECRET:-$JWT_SECRET}"

export GOTRUE_EXTERNAL_EMAIL_ENABLED="${GOTRUE_EXTERNAL_EMAIL_ENABLED:-$ENABLE_EMAIL_SIGNUP}"
export GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED="${GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED:-$ENABLE_ANONYMOUS_USERS}"

export GOTRUE_SMTP_ADMIN_EMAIL="${GOTRUE_SMTP_ADMIN_EMAIL:-$SMTP_ADMIN_EMAIL}"
export GOTRUE_SMTP_ADMIN_EMAIL="${GOTRUE_SMTP_ADMIN_EMAIL:-$SMTP_ADMIN_EMAIL}"
export GOTRUE_SMTP_HOST="${GOTRUE_SMTP_HOST:-$SMTP_HOST}"
export GOTRUE_SMTP_PORT="${GOTRUE_SMTP_PORT:-$SMTP_PORT}"
export GOTRUE_SMTP_USER="${GOTRUE_SMTP_USER:-$SMTP_USER}"
export GOTRUE_SMTP_PASS="${GOTRUE_SMTP_PASS:-$SMTP_PASS}"
export GOTRUE_SMTP_SENDER_NAME="${GOTRUE_SMTP_SENDER_NAME:-$SMTP_SENDER_NAME}"

export GOTRUE_MAILER_AUTOCONFIRM="${GOTRUE_MAILER_AUTOCONFIRM:-$ENABLE_EMAIL_AUTOCONFIRM}"
export GOTRUE_MAILER_URLPATHS_INVITE="${GOTRUE_MAILER_URLPATHS_INVITE:-$MAILER_URLPATHS_INVITE}"
export GOTRUE_MAILER_URLPATHS_CONFIRMATION="${GOTRUE_MAILER_URLPATHS_CONFIRMATION:-$MAILER_URLPATHS_CONFIRMATION}"
export GOTRUE_MAILER_URLPATHS_RECOVERY="${GOTRUE_MAILER_URLPATHS_RECOVERY:-$MAILER_URLPATHS_RECOVERY}"
export GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE="${GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE:-$MAILER_URLPATHS_EMAIL_CHANGE}"

export GOTRUE_EXTERNAL_PHONE_ENABLED="${GOTRUE_EXTERNAL_PHONE_ENABLED:-$ENABLE_PHONE_SIGNUP}"
export GOTRUE_SMS_AUTOCONFIRM="${GOTRUE_SMS_AUTOCONFIRM:-$ENABLE_PHONE_AUTOCONFIRM}"

exec "${@}"