#!/usr/bin/env bash
set -Eeuo pipefail

export IMGPROXY_BIND="${IMGPROXY_BIND:-:5001}"
export IMGPROXY_LOCAL_FILESYSTEM_ROOT="${IMGPROXY_LOCAL_FILESYSTEM_ROOT:-/}"
export IMGPROXY_USE_ETAG="${IMGPROXY_USE_ETAG:-true}"
export IMGPROXY_ENABLE_WEBP_DETECTION="${IMGPROXY_ENABLE_WEBP_DETECTION:-true}"
export IMGPROXY_MAX_SRC_RESOLUTION="${IMGPROXY_MAX_SRC_RESOLUTION:-16.8}"

exec "${@}"