#!/usr/bin/env bash
set -Eeuo pipefail

export AUTH_JWT_SECRET="${AUTH_JWT_SECRET:-$JWT_SECRET}"
export DEFAULT_ORGANIZATION_NAME="${DEFAULT_ORGANIZATION_NAME:-$STUDIO_DEFAULT_ORGANIZATION}"
export DEFAULT_PROJECT_NAME="${DEFAULT_PROJECT_NAME:-$STUDIO_DEFAULT_PROJECT}"
export SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-$ANON_KEY}"
export SUPABASE_SERVICE_KEY="${SUPABASE_SERVICE_KEY:-$SERVICE_ROLE_KEY}"
export LOGFLARE_API_KEY="${LOGFLARE_API_KEY:-$LOGFLARE_PUBLIC_ACCESS_TOKEN}"

exec docker-entrypoint.sh "${@}"