#!/usr/bin/env bash
set -Eeuo pipefail

export HOSTNAME="${HOSTNAME:-::}"

export STUDIO_PG_META_URL="${STUDIO_PG_META_URL:-http://meta:8080}"
export LOGFLARE_URL="${LOGFLARE_URL:-http://analytics:4000}"
export SUPABASE_URL="${SUPABASE_URL:-http://studio:3000}"
export SUPABASE_PUBLIC_URL="${SUPABASE_PUBLIC_URL:-http://localhost:8000}"

export NEXT_PUBLIC_ENABLE_LOGS="${NEXT_PUBLIC_ENABLE_LOGS:-false}"
export NEXT_ANALYTICS_BACKEND_PROVIDER="${NEXT_ANALYTICS_BACKEND_PROVIDER:-postgres}"

export SNIPPETS_MANAGEMENT_FOLDER="${SNIPPETS_MANAGEMENT_FOLDER:-/app/snippets}"
export EDGE_FUNCTIONS_MANAGEMENT_FOLDER="${EDGE_FUNCTIONS_MANAGEMENT_FOLDER:-/app/edge-functions}"

export OPENAI_API_KEY="${OPENAI_API_KEY:-}"
export NEXT_PUBLIC_ENABLE_LOGS="${NEXT_PUBLIC_ENABLE_LOGS:-true}"

export STUDIO_DEFAULT_ORGANIZATION="${STUDIO_DEFAULT_ORGANIZATION:-Default Organization}"
export STUDIO_DEFAULT_PROJECT="${STUDIO_DEFAULT_PROJECT:-Default Project}"

export AUTH_JWT_SECRET="${AUTH_JWT_SECRET:-$JWT_SECRET}"
export DEFAULT_ORGANIZATION_NAME="${DEFAULT_ORGANIZATION_NAME:-$STUDIO_DEFAULT_ORGANIZATION}"
export DEFAULT_PROJECT_NAME="${DEFAULT_PROJECT_NAME:-$STUDIO_DEFAULT_PROJECT}"
export SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-$ANON_KEY}"
export SUPABASE_SERVICE_KEY="${SUPABASE_SERVICE_KEY:-$SERVICE_ROLE_KEY}"
export LOGFLARE_API_KEY="${LOGFLARE_API_KEY:-$LOGFLARE_PUBLIC_ACCESS_TOKEN}"

exec "${@}"