#!/usr/bin/env bash
set -Eeuo pipefail

export DB_HOSTNAME="${DB_HOSTNAME:-$POSTGRES_HOST}"
export DB_PORT="${DB_PORT:-$POSTGRES_PORT}"
export DB_PASSWORD="${DB_PASSWORD:-$POSTGRES_PASSWORD}"
export POSTGRES_BACKEND_URL="${POSTGRES_BACKEND_URL:-postgresql://${DB_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_DATABASE}}"

exec "${@}"