#!/usr/bin/env bash
set -Eeuo pipefail

export PGRST_DB_URI="${PGRST_DB_URI:-postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"
export PGRST_JWT_SECRET="${PGRST_JWT_SECRET:-$JWT_SECRET}"
export PGRST_APP_SETTINGS_JWT_SECRET="${PGRST_APP_SETTINGS_JWT_SECRET:-$JWT_SECRET}"
export PGRST_APP_SETTINGS_JWT_EXP="${PGRST_APP_SETTINGS_JWT_EXP:-$JWT_EXPIRY}"

exec "${@}"